import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { GLOSSARY } from "../lib/ai/advisory-chat.ts";
import { metricInfo } from "../lib/metric-glossary.ts";
import { TERMINOLOGY, renderTerminologyMarkdown, terminology } from "../lib/terminology.ts";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const required = [
  "nbbo", "occ", "mfe", "mae", "expectancy", "profit_factor", "baseline", "shadow",
  "winner_retention", "loss_rejection", "evidence_quality", "independent_sessions",
  "reward_remaining", "move_consumed", "discovery_stage", "setup_episode",
  "forward_label", "evidence_coverage", "dataset_version",
  "historical_analog", "expected_value", "counterfactual", "paper_trade",
];

test("canonical terminology has all required typed fields", () => {
  for (const id of required) {
    const entry = TERMINOLOGY[id];
    assert.ok(entry, `missing ${id}`);
    for (const field of ["id", "label", "shortDefinition", "fullDefinition", "interpretation", "authority", "pointInTimeCaveat", "evidenceRequirement", "aliases", "version"]) {
      assert.notEqual(entry[field], undefined, `${id}.${field}`);
    }
    assert.equal(entry.version, "TERMINOLOGY_V1");
  }
});

test("app tooltips and Ask OptiScan resolve shared terms from the registry", () => {
  assert.equal(metricInfo("discoveryStage").what, TERMINOLOGY.discovery_stage.shortDefinition);
  assert.equal(metricInfo("exactOcc").what, TERMINOLOGY.occ.shortDefinition);
  assert.equal(metricInfo("expectedValue").what, TERMINOLOGY.expected_value.shortDefinition);
  assert.match(GLOSSARY.MFE, new RegExp(TERMINOLOGY.mfe.shortDefinition.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(GLOSSARY["capture efficiency"], /how much of a trade's best available gain/);
  assert.equal(terminology("national best bid and offer")?.id, "nbbo");
});

test("Obsidian glossary is generated byte-for-byte from the registry", () => {
  const file = path.join(root, "docs", "brain", "02 Components", "CANONICAL_TERMINOLOGY.md");
  assert.equal(fs.readFileSync(file, "utf8"), renderTerminologyMarkdown());
});

test("discovery-stage wording names V2 and no longer repeats the stale 1.6-second V1 conclusion", () => {
  const info = metricInfo("discoveryStage");
  assert.match(info.what, /PRE_MOVE_DISCOVERY_V2/);
  assert.doesNotMatch(`${info.what} ${info.risk}`, /1\.6[- ]second/i);
});
