/**
 * Canonical OptiScan terminology registry.
 *
 * Shared concepts live here once. UI metric cards may still have local display
 * metrics, but any term used by the app, Ask OptiScan, and project memory must
 * resolve through this typed, versioned authority.
 */
import type { MetricInfo } from "./metric-glossary.ts";

export interface TerminologyEntry {
  id: string;
  label: string;
  shortDefinition: string;
  fullDefinition: string;
  formula: string | null;
  unit: string | null;
  interpretation: string;
  authority: "MARKET_STANDARD" | "OPTISCAN_EVIDENCE" | "OPTISCAN_RESEARCH_GOVERNANCE";
  entryConvention: string | null;
  pointInTimeCaveat: string;
  evidenceRequirement: string;
  aliases: readonly string[];
  version: "TERMINOLOGY_V1";
  legacyMetricKey: string;
}

const t = (entry: Omit<TerminologyEntry, "version">): TerminologyEntry => Object.freeze({ ...entry, version: "TERMINOLOGY_V1" });

export const TERMINOLOGY = Object.freeze({
  nbbo: t({ id: "nbbo", label: "NBBO", shortDefinition: "The best displayed US option bid and ask available at that moment.", fullDefinition: "National Best Bid and Offer: the highest displayed bid and lowest displayed ask across reporting US venues for the exact contract.", formula: "max(venue bids) / min(venue asks)", unit: "price", interpretation: "Tighter and fresher is generally more executable.", authority: "MARKET_STANDARD", entryConvention: "A buy-at-ask label must use the contemporaneous ask; exits must name their bid/mid convention.", pointInTimeCaveat: "A later NBBO cannot be substituted for the evaluation-time quote.", evidenceRequirement: "Exact OCC, bid, ask, provider timestamp, observation timestamp, and freshness policy.", aliases: ["national best bid and offer", "best bid/ask"], legacyMetricKey: "nbbo" }),
  occ: t({ id: "occ", label: "OCC contract", shortDefinition: "The exact standardized option identity: underlying, expiry, side, and strike.", fullDefinition: "The exact option symbol used to prevent marks, trades, or outcomes from a nearby contract being joined to the evaluated contract.", formula: null, unit: null, interpretation: "Identity must match exactly; similarity is not enough.", authority: "MARKET_STANDARD", entryConvention: null, pointInTimeCaveat: "The contract must be frozen at evaluation; re-selection after the outcome is leakage.", evidenceRequirement: "Exact normalized OCC plus session and episode/case identity.", aliases: ["exact OCC", "option symbol", "contract identity"], legacyMetricKey: "exactOcc" }),
  mfe: t({ id: "mfe", label: "MFE", shortDefinition: "The greatest favorable return observed after the frozen entry.", fullDefinition: "Maximum favorable excursion over a declared forward horizon, computed from the exact instrument and executable mark convention.", formula: "max(forward executable return)", unit: "%", interpretation: "Higher means more favorable movement was available, not that it was realized.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Must name entry and forward exit marks, such as buy at ask and mark at future bid.", pointInTimeCaveat: "MFE is a forward label and is forbidden from the episode's evaluation-time state.", evidenceRequirement: "Sufficient forward coverage with exact identity; otherwise null/censored.", aliases: ["maximum favorable excursion"], legacyMetricKey: "mfe" }),
  mae: t({ id: "mae", label: "MAE", shortDefinition: "The greatest adverse return observed after the frozen entry.", fullDefinition: "Maximum adverse excursion over a declared forward horizon, computed from the exact instrument and executable mark convention.", formula: "min(forward executable return)", unit: "%", interpretation: "Closer to zero means less adverse movement; it is not automatically a stop recommendation.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Must use the same declared entry/mark convention as the outcome family.", pointInTimeCaveat: "MAE is a forward label and is forbidden from evaluation-time features.", evidenceRequirement: "Sufficient forward coverage with exact identity; otherwise null/censored.", aliases: ["maximum adverse excursion"], legacyMetricKey: "mae" }),
  expectancy: t({ id: "expectancy", label: "Expectancy", shortDefinition: "The sample's average return per observation or trade.", fullDefinition: "The arithmetic mean of realized or explicitly labeled returns for one named population, convention, and horizon.", formula: "mean(return) = win_rate×avg_win − loss_rate×avg_loss", unit: "% or currency per observation", interpretation: "Positive is favorable only when sample quality, independence, and tail dependence are acceptable.", authority: "OPTISCAN_EVIDENCE", entryConvention: "All returns in the population must share an explicit convention.", pointInTimeCaveat: "Historical expectancy may inform research but cannot be inserted as a future fact in a frozen episode.", evidenceRequirement: "Named cohort, sample size, independent sessions, coverage, censoring, and tail diagnostics.", aliases: ["expected return", "average return per trade"], legacyMetricKey: "expectancy" }),
  profit_factor: t({ id: "profit_factor", label: "Profit factor", shortDefinition: "Gross gains divided by the absolute value of gross losses.", fullDefinition: "A cohort-level payoff statistic that must be reported with sample size and sensitivity to the largest winner.", formula: "sum(positive returns) / abs(sum(negative returns))", unit: "ratio", interpretation: "Above 1 means measured gains exceeded losses; it does not prove durable edge.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Population returns must use one consistent convention.", pointInTimeCaveat: "Computed only after outcomes exist, and one unusually large winner can make an otherwise weak population look durable.", evidenceRequirement: "Closed supported outcomes, PF excluding best winner, independent sessions, and cohort definition.", aliases: ["PF", "profit factor"], legacyMetricKey: "profitFactor" }),
  baseline: t({ id: "baseline", label: "Baseline", shortDefinition: "The frozen comparison rule or population an experiment must beat.", fullDefinition: "The predeclared control used to measure whether a shadow rule improves losses without sacrificing winners or changing the eligible population.", formula: null, unit: null, interpretation: "A comparison is invalid if the baseline population or period changes after results are seen.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: null, pointInTimeCaveat: "Freeze before prospective outcomes accrue.", evidenceRequirement: "Version/hash, population, dates, inclusion rules, and unchanged comparator.", aliases: ["control", "benchmark arm"], legacyMetricKey: "baseline" }),
  shadow: t({ id: "shadow", label: "Shadow", shortDefinition: "Measured prospectively without changing live authority or delivery.", fullDefinition: "A parallel evaluation recorded at decision time so it can be compared later while leaving strategies, gates, subscribers, and execution unchanged.", formula: null, unit: null, interpretation: "Shadow evidence can support human review; it cannot authorize itself.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: null, pointInTimeCaveat: "Definition and hash must be frozen before outcomes.", evidenceRequirement: "Immutable definition/hash, prospective registration, population identity, and outcome coverage.", aliases: ["shadow experiment", "research only"], legacyMetricKey: "shadow" }),
  winner_retention: t({ id: "winner_retention", label: "Winner retention", shortDefinition: "The share of baseline winners an experimental filter would keep.", fullDefinition: "The cost side of a proposed filter, always reported beside loss rejection on the same eligible population.", formula: "kept baseline winners / all baseline winners", unit: "%", interpretation: "Higher is better, but uncertainty matters with few winners.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: null, pointInTimeCaveat: "The filter must be fixed before prospective outcomes are labeled.", evidenceRequirement: "Same eligible population for baseline and shadow, with missing evidence excluded rather than called rejected.", aliases: ["winner keep rate"], legacyMetricKey: "winnerRetention" }),
  loss_rejection: t({ id: "loss_rejection", label: "Loss rejection", shortDefinition: "The share of baseline losses an experimental filter would avoid.", fullDefinition: "The measured benefit of a proposed filter, meaningful only with winner retention on the same population.", formula: "rejected baseline losses / all baseline losses", unit: "%", interpretation: "Higher is favorable only if winner retention remains acceptable.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: null, pointInTimeCaveat: "The filter must be fixed before prospective outcomes are labeled; this number is meaningless without winner retention beside it.", evidenceRequirement: "Same eligible population, complete outcome accounting, and explicit unknown bucket.", aliases: ["loser rejection"], legacyMetricKey: "lossRejection" }),
  evidence_quality: t({ id: "evidence_quality", label: "Evidence quality", shortDefinition: "How strongly the stored provenance and coverage support a measurement.", fullDefinition: "A structural status describing identity, timestamps, entry convention, forward coverage, censoring, sample independence, and source reliability.", formula: null, unit: null, interpretation: "Verified exact evidence is strongest; missing is unknown, never zero.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Included in the quality assessment.", pointInTimeCaveat: "Quality at evaluation and quality of later labels are separate fields.", evidenceRequirement: "Provenance, as-of time, quality status, and missing reason for every canonical value.", aliases: ["data quality", "evidence grade"], legacyMetricKey: "evidenceQuality" }),
  independent_sessions: t({ id: "independent_sessions", label: "Independent sessions", shortDefinition: "The number of distinct validated trading sessions represented.", fullDefinition: "A guard against treating many observations from one market day as independent repetitions of an effect.", formula: "count(distinct validated trading_session)", unit: "sessions", interpretation: "More regime-diverse sessions generally strengthen evidence.", authority: "OPTISCAN_EVIDENCE", entryConvention: null, pointInTimeCaveat: "Session membership must come from contemporaneous timestamps and the exchange calendar.", evidenceRequirement: "Validated session dates; holidays and malformed dates do not count.", aliases: ["session count", "independent days"], legacyMetricKey: "independentSessions" }),
  reward_remaining: t({ id: "reward_remaining", label: "Reward remaining", shortDefinition: "The estimated favorable distance still available at evaluation under a declared target model.", fullDefinition: "A point-in-time feature comparing current state with a target known at evaluation; it is not the later maximum return.", formula: "remaining target distance / total modeled target distance", unit: "ratio or %", interpretation: "Higher may mean more room, but only after the feature demonstrates out-of-sample discrimination.", authority: "OPTISCAN_EVIDENCE", entryConvention: null, pointInTimeCaveat: "Target inputs must be frozen at T0; the current near-constant implementation has not discriminated anything yet, and no session high or later outcome may enter.", evidenceRequirement: "Frozen target method/version and nondegeneracy checks.", aliases: ["remaining opportunity"], legacyMetricKey: "rewardRemaining" }),
  move_consumed: t({ id: "move_consumed", label: "Move consumed", shortDefinition: "The direction-signed share of a modeled move already completed at evaluation.", fullDefinition: "A point-in-time chase feature; bullish and bearish movement must be signed consistently and must not use later extrema.", formula: "consumed favorable distance / modeled total distance", unit: "ratio or %", interpretation: "Lower generally means earlier, provided the denominator is legitimate.", authority: "OPTISCAN_EVIDENCE", entryConvention: null, pointInTimeCaveat: "Use only levels known at T0; later HOD/LOD is leakage.", evidenceRequirement: "Direction, frozen origin/target, formula version, and valid denominator.", aliases: ["confirmation cost", "move already used"], legacyMetricKey: "moveConsumed" }),
  discovery_stage: t({ id: "discovery_stage", label: "Discovery stage", shortDefinition: "The frozen PRE_MOVE_DISCOVERY_V2 stage at which OptiScan observed the opportunity.", fullDefinition: "A prospective stage classification from the frozen PRE_MOVE_DISCOVERY_V2 definition; it describes state at observation and is evaluated only after independent forward outcomes accrue.", formula: null, unit: null, interpretation: "Earlier is useful only when later confirmation and executable outcomes support it.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: null, pointInTimeCaveat: "Never recompute the stage using later prices; use the frozen definition hash.", evidenceRequirement: "Prospective V2 capture, frozen hash, valid T0 fields, closed outcomes, and independent sessions.", aliases: ["pre-move stage", "earliness stage"], legacyMetricKey: "discoveryStage" }),
  setup_episode: t({ id: "setup_episode", label: "Setup episode", shortDefinition: "An immutable point-in-time record of what OptiScan knew and decided at T0.", fullDefinition: "SetupEpisodeV2 stores provenance-bearing underlying, option, and OptiScan state separately from actions and forward outcome labels.", formula: null, unit: null, interpretation: "It is the canonical market-memory unit, not necessarily a trade.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Exact-option evidence names its contract and quote convention.", pointInTimeCaveat: "Zone A rejects future timestamps and outcome fields.", evidenceRequirement: "Durable identity, T0, config digest, feature versions, provenance, and explicit missing reasons.", aliases: ["episode", "SetupEpisodeV2"], legacyMetricKey: "setupEpisode" }),
  historical_analog: t({ id: "historical_analog", label: "Historical analog", shortDefinition: "A prior point-in-time setup judged similar under a frozen comparison method.", fullDefinition: "A historical SetupEpisode state used for empirical next-event evidence without importing its outcome into the current feature vector.", formula: null, unit: null, interpretation: "Useful only with adequate independent samples and stable similarity features.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Outcome comparisons must use compatible instruments and conventions.", pointInTimeCaveat: "Similarity uses Zone A only; outcomes remain labels.", evidenceRequirement: "Point-in-time-safe episodes, frozen similarity version, distances, sample/session counts, and drift checks.", aliases: ["analog", "nearest historical setup"], legacyMetricKey: "historicalAnalog" }),
  expected_value: t({ id: "expected_value", label: "Expected value", shortDefinition: "The probability-weighted mean payoff for one declared action and horizon.", fullDefinition: "A deterministic empirical estimate from actual forward labels, including adverse outcomes and costs; it is not an LLM opinion.", formula: "sum(probability_i × payoff_i) − modeled costs", unit: "% or currency per opportunity", interpretation: "Positive is favorable only when calibrated, stable, and supported out of sample.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Entry, exit, spread, and cost conventions must be explicit.", pointInTimeCaveat: "At live T0, only a precomputed historical estimate may be read; current future outcomes are unavailable.", evidenceRequirement: "Calibrated empirical distribution, sample/session count, quality, drift, and uncertainty.", aliases: ["EV", "expected return"], legacyMetricKey: "expectedValue" }),
  capture_efficiency: t({ id: "capture_efficiency", label: "Capture efficiency", shortDefinition: "Capture efficiency measures how much of a trade's best available gain the exit policy actually kept.", fullDefinition: "It compares realized return with MFE under compatible entry and marking conventions.", formula: "realized favorable return / MFE", unit: "%", interpretation: "Higher means more of the available favorable excursion was retained.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Realized return and MFE must share the same frozen entry basis.", pointInTimeCaveat: "This is a post-outcome management label, never an evaluation-time feature.", evidenceRequirement: "Realized return, MFE, exact identity, and compatible conventions.", aliases: ["capture efficiency"], legacyMetricKey: "captureEfficiency" }),
  delta_band: t({ id: "delta_band", label: "Delta band", shortDefinition: "The permitted range of option delta used by a contract-selection policy.", fullDefinition: "It constrains contract sensitivity for one strategy/version and is not itself a probability forecast.", formula: "min_delta ≤ abs(delta) ≤ max_delta", unit: "delta", interpretation: "Inside means eligible for that selector rule; outside does not mean intrinsically bad.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: null, pointInTimeCaveat: "Use the delta available with the evaluation-time contract evidence.", evidenceRequirement: "Exact contract, delta source/as-of time, and selector version.", aliases: ["delta band", "delta range"], legacyMetricKey: "delta" }),
  t1: t({ id: "t1", label: "T1", shortDefinition: "The first profit target frozen for a paper or delivered trade.", fullDefinition: "T1 is a target level defined by the governing strategy/exit policy at entry.", formula: null, unit: "option price", interpretation: "A target is a policy level, not a guaranteed outcome.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: "Frozen from the same entry policy as the trade.", pointInTimeCaveat: "It may not be moved after seeing the outcome when evaluating policy performance.", evidenceRequirement: "Strategy/config version, entry basis, and frozen target value.", aliases: ["first target"], legacyMetricKey: "t1" }),
  t2: t({ id: "t2", label: "T2", shortDefinition: "The second, farther profit target frozen for a paper or delivered trade.", fullDefinition: "T2 is a farther target level defined by the governing strategy/exit policy at entry.", formula: null, unit: "option price", interpretation: "A target is a policy level, not a guaranteed outcome.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: "Frozen from the same entry policy as the trade.", pointInTimeCaveat: "It may not be moved after seeing the outcome when evaluating policy performance.", evidenceRequirement: "Strategy/config version, entry basis, and frozen target value.", aliases: ["second target"], legacyMetricKey: "t2" }),
  zero_dte: t({ id: "zero_dte", label: "0DTE", shortDefinition: "An option whose expiration date is the current trading day.", fullDefinition: "A same-day-expiry contract with high gamma and rapid time decay; strategy permissions remain separately versioned.", formula: "expiration_date = trading_date", unit: null, interpretation: "A horizon/risk class, not a quality rating.", authority: "MARKET_STANDARD", entryConvention: null, pointInTimeCaveat: "DTE must be computed from the evaluation session and exact expiration.", evidenceRequirement: "Exact OCC, expiration, trading session, and DTE calculation.", aliases: ["same-day expiry"], legacyMetricKey: "zeroDte" }),
  vwap: t({ id: "vwap", label: "VWAP", shortDefinition: "The session's volume-weighted average underlying price through the evaluation time.", fullDefinition: "VWAP summarizes traded price weighted by volume using only bars available through T0.", formula: "sum(typical_price × volume) / sum(volume)", unit: "underlying price", interpretation: "Price relative to VWAP can describe session control; it is not sufficient alone.", authority: "MARKET_STANDARD", entryConvention: null, pointInTimeCaveat: "Only bars ending by T0 may enter; extended-hours inclusion must be explicit.", evidenceRequirement: "Timestamped underlying bars, session convention, and formula version.", aliases: ["volume-weighted average price"], legacyMetricKey: "vwap" }),
  counterfactual: t({ id: "counterfactual", label: "Counterfactual", shortDefinition: "A defensible setup that was observed but not actually traded.", fullDefinition: "A structurally separate research action recording what would be measured under an exact contract and explicit entry convention.", formula: null, unit: null, interpretation: "It can teach opportunity quality but must never be reported as an actual trade.", authority: "OPTISCAN_RESEARCH_GOVERNANCE", entryConvention: "Requires exact OCC and defensible contemporaneous entry.", pointInTimeCaveat: "Eligibility and entry are frozen before outcomes.", evidenceRequirement: "Observation episode, exact contract, fresh executable quote, explicit convention, and no paper/trade claim.", aliases: ["would-have-traded", "untraded eligible setup"], legacyMetricKey: "counterfactual" }),
  paper_trade: t({ id: "paper_trade", label: "Paper trade", shortDefinition: "An actual simulated position created under the paper policy.", fullDefinition: "A structurally recorded simulated action with its own entry, position lifecycle, marks, and exits; it is distinct from observations and counterfactuals.", formula: null, unit: null, interpretation: "Useful forward evidence, but simulated fills are not live-money fills.", authority: "OPTISCAN_EVIDENCE", entryConvention: "Uses the frozen paper entry/exit policy recorded with the action.", pointInTimeCaveat: "The action time and entry cannot be backfilled from later favorable marks.", evidenceRequirement: "Paper action row, exact identity, fill convention, timestamps, and complete outcome coverage.", aliases: ["simulated trade", "paper position"], legacyMetricKey: "paperTrade" }),
} satisfies Record<string, TerminologyEntry>);

export type TerminologyId = keyof typeof TERMINOLOGY;

export function terminology(idOrAlias: string): TerminologyEntry | null {
  const needle = idOrAlias.trim().toLowerCase();
  return Object.values(TERMINOLOGY).find((entry) =>
    entry.id.toLowerCase() === needle
    || entry.label.toLowerCase() === needle
    || entry.legacyMetricKey.toLowerCase() === needle
    || entry.aliases.some((alias) => alias.toLowerCase() === needle)
  ) ?? null;
}

export function terminologyMetricInfo(entry: TerminologyEntry): MetricInfo {
  return {
    label: entry.label,
    what: entry.shortDefinition,
    why: entry.fullDefinition,
    direction: entry.interpretation,
    scoring: entry.evidenceRequirement,
    risk: entry.pointInTimeCaveat,
  };
}

export function canonicalMetricGlossary(): Record<string, MetricInfo> {
  return Object.fromEntries(Object.values(TERMINOLOGY).map((entry) => [entry.legacyMetricKey, terminologyMetricInfo(entry)]));
}

export function askOptiscanGlossary(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const entry of Object.values(TERMINOLOGY)) {
    const definition = `${entry.label}: ${entry.shortDefinition}`;
    out[entry.label] = definition;
    out[entry.id] = definition;
    for (const alias of entry.aliases) out[alias] = definition;
  }
  return out;
}

export function renderTerminologyMarkdown(): string {
  const lines = [
    "# Canonical OptiScan Terminology",
    "",
    "> GENERATED from `lib/terminology.ts`. Do not hand-edit definitions here.",
    "",
    "Registry version: `TERMINOLOGY_V1`",
    "",
  ];
  for (const entry of Object.values(TERMINOLOGY)) {
    lines.push(`## ${entry.label}`, "", entry.fullDefinition, "");
    if (entry.formula) lines.push(`- Formula: \`${entry.formula}\``);
    if (entry.unit) lines.push(`- Unit: ${entry.unit}`);
    lines.push(
      `- Interpretation: ${entry.interpretation}`,
      `- Authority: \`${entry.authority}\``,
      `- Entry convention: ${entry.entryConvention ?? "Not applicable"}`,
      `- Point-in-time caveat: ${entry.pointInTimeCaveat}`,
      `- Evidence requirement: ${entry.evidenceRequirement}`,
      `- Aliases: ${entry.aliases.join(", ") || "None"}`,
      "",
    );
  }
  return `${lines.join("\n").trim()}\n`;
}
