/**
 * Demo overnight recommendations for UI review / Discord screenshot fixtures.
 */
import type { OvernightPlan } from "../research/overnight/next-session-plan.ts";

export const DEMO_OVERNIGHT_PLAN: OvernightPlan = {
  tradingDay: "2026-07-28",
  builtAtMs: Date.now(),
  planVersion: "overnight-v1-demo",
  marketContext: {
    spyNote: "SPY: prior close structure intact; AH drift mild",
    qqqNote: "QQQ: relative strength vs SPY into close",
    newsNote: "News/earnings: UNAVAILABLE unless separately sourced — never invented",
  },
  recommendations: [
    {
      symbol: "SPY",
      bias: "bullish",
      setupFamily: "orb_continuation",
      triggerLevel: 634.5,
      invalidationLevel: 631.2,
      preferredDteRange: "0–1",
      preferredMoneyness: "ATM",
      contractSelectionGuidance: "Prefer liquid near-ATM calls after open; re-check spread ≤10%",
      confidence: 82,
      supportingEvidence: ["Prior-day ORB high held", "Relative volume elevated into close", "Quant sample n=42"],
      mainRisk: "Gap below invalidation at open",
      verifyContractAfterOpen: true,
      quoteContext: "STALE_PRIOR_SESSION",
      executable: false,
      rank: 1,
      priorContractContext: "O:SPY260727C00635000",
    },
    {
      symbol: "NVDA",
      bias: "bullish",
      setupFamily: "vwap_reclaim",
      triggerLevel: 177.2,
      invalidationLevel: 174.8,
      preferredDteRange: "0–5",
      preferredMoneyness: "ATM",
      contractSelectionGuidance: "Near-ATM call; avoid wide AH prints",
      confidence: 74,
      supportingEvidence: ["VWAP reclaim attempt", "Semiconductor relative strength"],
      mainRisk: "Sector fade at open",
      verifyContractAfterOpen: true,
      quoteContext: "STALE_PRIOR_SESSION",
      executable: false,
      rank: 2,
      priorContractContext: null,
    },
    {
      symbol: "QQQ",
      bias: "bullish",
      setupFamily: "gap_hold",
      triggerLevel: 568,
      invalidationLevel: 564.5,
      preferredDteRange: "0–5",
      preferredMoneyness: "OTM",
      contractSelectionGuidance: "Slight OTM if gap holds; ATM if choppy",
      confidence: 69,
      supportingEvidence: ["Prior resistance retest", "QQQ vs SPY RS"],
      mainRisk: "Open drive without structure",
      verifyContractAfterOpen: true,
      quoteContext: "STALE_PRIOR_SESSION",
      executable: false,
      rank: 3,
      priorContractContext: null,
    },
  ],
};
